name: knovator_task
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Responsive UI
  flutter_screenutil: ^5.9.0

  # Utils
  image_picker: ^1.0.7
  fluttertoast: ^8.2.5
  url_launcher: ^6.2.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
flutter:

  uses-material-design: true